In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train=pd.read_csv('train.csv')

In [4]:
test=pd.read_csv('test.csv')

In [5]:
train.head()

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,H14663,2013,1.0,0,N,V,V,U,290.0,1,1960.0,.,1053,0
1,H2037,2015,1.0,0,V,N,O,R,490.0,1,1850.0,4,1053,0
2,H3802,2014,1.0,0,N,V,V,U,595.0,1,1960.0,.,1053,0
3,H3834,2013,1.0,0,V,V,V,U,2840.0,1,1960.0,.,1053,0
4,H5053,2014,1.0,0,V,N,O,R,680.0,1,1800.0,3,1053,0

In [6]:
test.head()

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code
0,H11920,2013,1.000000,0,V,N,O,R,300.0,1,1960.0,3,3310
1,H11921,2016,0.997268,0,V,N,O,R,300.0,1,1960.0,3,3310
2,H9805,2013,0.369863,0,V,V,V,U,790.0,1,1960.0,.,3310
3,H7493,2014,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321
4,H7494,2016,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321

In [8]:
train.shape

(7160, 14)

In [9]:
test.shape

(3069, 13)

In [11]:
train.columns

Index(['Customer Id', 'YearOfObservation', 'Insured_Period', 'Residential',
       'Building_Painted', 'Building_Fenced', 'Garden', 'Settlement',
       'Building Dimension', 'Building_Type', 'Date_of_Occupancy',
       'NumberOfWindows', 'Geo_Code', 'Claim'],
      dtype='object')

In [12]:
test.columns

Index(['Customer Id', 'YearOfObservation', 'Insured_Period', 'Residential',
       'Building_Painted', 'Building_Fenced', 'Garden', 'Settlement',
       'Building Dimension', 'Building_Type', 'Date_of_Occupancy',
       'NumberOfWindows', 'Geo_Code'],
      dtype='object')

In [13]:
train.isnull().sum

<bound method DataFrame.sum of       Customer Id  YearOfObservation  Insured_Period  Residential  \
0           False              False           False        False
1           False              False           False        False
2           False              False           False        False
3           False              False           False        False
4           False              False           False        False
5           False              False           False        False
6           False              False           False        False
7           False              False           False        False
8           False              False           False        False
9           False              False           False        False
10          False              False           False        False
11          False              False           False        False
12          False              False           False        False
13          False              False           False        False
14          False              False           False        False
15          False              False           False        False
16          False              False           False        False
17          False              False           False        False
18          False              False           False        False
19          False              False           False        False
20          False              False           False        False
21          False              False           False        False
22          False              False           False        False
23          False              False           False        False
24          False              False           False        False
25          False              False           False        False
26          False              False           False        False
27          False              False           False        False
28          False              False           False        False
29          False              False           False        False
...           ...                ...             ...          ...
7130        False              False           False        False
7131        False              False           False        False
7132        False              False           False        False
7133        False              False           False        False
7134        False              False           False        False
7135        False              False           False        False
7136        False              False           False        False
7137        False              False           False        False
7138        False              False           False        False
7139        False              False           False        False
7140        False              False           False        False
7141        False              False           False        False
7142        False              False           False        False
7143        False              False           False        False
7144        False              False           False        False
7145        False              False           False        False
7146        False              False           False        False
7147        False              False           False        False
7148        False              False           False        False
7149        False              False           False        False
7150        False              False           False        False
7151        False              False           False        False
7152        False              False           False        False
7153        False              False           False        False
7154        False              False           False        False
7155        False              False           False        False
7156        False              False           False        False
7157        False              False           False        False
7158        False              False           False        False
7159        False              False           False        False

      Building_Painted  Building_Fenced  Garden  Settlement  \
0                False            False   False       False
1                False            False   False       False
2                False            False   False       False
3                False            False   False       False
4                False            False   False       False
5                False            False   False       False
6                False            False   False       False
7                False            False   False       False
8                False            False   False       False
9                False            False   False       False
10               False            False   False       False
11               False            False   False       False
12               False            False   False       False
13               False            False   False       False
14               False            False   False       False
15               False            False   False       False
16               False            False   False       False
17               False            False   False       False
18               False            False   False       False
19               False            False   False       False
20               False            False   False       False
21               False            False   False       False
22               False            False   False       False
23               False            False   False       False
24               False            False   False       False
25               False            False   False       False
26               False            False   False       False
27               False            False   False       False
28               False            False   False       False
29               False            False   False       False
...                ...              ...     ...         ...
7130             False            False   False       False
7131             False            False   False       False
7132             False            False   False       False
7133             False            False   False       False
7134             False            False   False       False
7135             False            False   False       False
7136             False            False   False       False
7137             False            False   False       False
7138             False            False   False       False
7139             False            False   False       False
7140             False            False   False       False
7141             False            False   False       False
7142             False            False   False       False
7143             False            False   False       False
7144             False            False   False       False
7145             False            False   False       False
7146             False            False   False       False
7147             False            False   False       False
7148             False            False   False       False
7149             False            False   False       False
7150             False            False   False       False
7151             False            False   False       False
7152             False            False   False       False
7153             False            False   False       False
7154             False            False   False       False
7155             False            False   False       False
7156             False            False   False       False
7157             False            False   False       False
7158             False            False   False       False
7159             False            False   False       False

      Building Dimension  Building_Type  Date_of_Occupancy  NumberOfWindows  \
0                  False          False              False            False
1                  False          False              False            False
2                  False          False              False            False
3                  False          False              False            False
4                  False          False              False            False
5                  False          False              False            False
6                  False          False              False            False
7                  False          False              False            False
8                  False          False              False            False
9                  False          False              False            False
10                 False          False              False            False
11                 False          False              False            False
12                 False          False              False            False
13                 False          False              False            False
14                 False          False              False            False
15                 False          False              False            False
16                 False          False              False            False
17                 False          False              False            False
18                 False          False              False            False
19                 False          False              False            False
20                 False          False              False            False
21                 False          False              False            False
22                 False          False              False            False
23                 False          False              False            False
24                 False          False              False            False
25                 False          False              False            False
26                 False          False              False            False
27                 False          False              False            False
28                 False          False              False            False
29                 False          False              False            False
...                  ...            ...                ...              ...
7130                True          False              False            False
7131                True          False              False            False
7132                True          False              False            False
7133                True          False              False            False
7134                True          False              False            False
7135                True          False              False            False
7136                True          False              False            False
7137                True          False              False            False
7138                True          False              False            False
7139                True          False              False            False
7140                True          False              False            False
7141                True          False              False            False
7142                True          False              False            False
7143                True          False              False            False
7144                True          False              False            False
7145                True          False              False            False
7146                True          False              False            False
7147                True          False              False            False
7148                True          False              False            False
7149                True          False              False            False
7150                True          False              False            False
7151                True          False              False            False
7152                True          False              False            False
7153                True          False              False            False
7154                True          False              False            False
7155                True          False              False            False
7156                True          False              False            False
7157                True          False              False            False
7158                True          False              False            False
7159                True          False              False            False

      Geo_Code  Claim
0        False  False
1        False  False
2        False  False
3        False  False
4        False  False
5        False  False
6        False  False
7        False  False
8        False  False
9        False  False
10       False  False
11       False  False
12       False  False
13       False  False
14       False  False
15       False  False
16       False  False
17       False  False
18       False  False
19       False  False
20       False  False
21       False  False
22       False  False
23       False  False
24       False  False
25       False  False
26       False  False
27       False  False
28       False  False
29       False  False
...        ...    ...
7130      True  False
7131      True  False
7132      True  False
7133      True  False
7134      True  False
7135      True  False
7136      True  False
7137      True  False
7138      True  False
7139      True  False
7140      True  False
7141      True  False
7142      True  False
7143      True  False
7144      True  False
7145      True  False
7146      True  False
7147      True  False
7148      True  False
7149      True  False
7150      True  False
7151      True  False
7152      True  False
7153      True  False
7154      True  False
7155      True  False
7156      True  False
7157      True  False
7158      True  False
7159      True  False

[7160 rows x 14 columns]>

In [14]:
test.isnull().sum

<bound method DataFrame.sum of       Customer Id  YearOfObservation  Insured_Period  Residential  \
0           False              False           False        False
1           False              False           False        False
2           False              False           False        False
3           False              False           False        False
4           False              False           False        False
5           False              False           False        False
6           False              False           False        False
7           False              False           False        False
8           False              False           False        False
9           False              False           False        False
10          False              False           False        False
11          False              False           False        False
12          False              False           False        False
13          False              False           False        False
14          False              False           False        False
15          False              False           False        False
16          False              False           False        False
17          False              False           False        False
18          False              False           False        False
19          False              False           False        False
20          False              False           False        False
21          False              False           False        False
22          False              False           False        False
23          False              False           False        False
24          False              False           False        False
25          False              False           False        False
26          False              False           False        False
27          False              False           False        False
28          False              False           False        False
29          False              False           False        False
...           ...                ...             ...          ...
3039        False              False           False        False
3040        False              False           False        False
3041        False              False           False        False
3042        False              False           False        False
3043        False              False           False        False
3044        False              False           False        False
3045        False              False           False        False
3046        False              False           False        False
3047        False              False           False        False
3048        False              False           False        False
3049        False              False           False        False
3050        False              False           False        False
3051        False              False           False        False
3052        False              False           False        False
3053        False              False           False        False
3054        False              False           False        False
3055        False              False           False        False
3056        False              False           False        False
3057        False              False           False        False
3058        False              False           False        False
3059        False              False           False        False
3060        False              False           False        False
3061        False              False           False        False
3062        False              False           False        False
3063        False              False           False        False
3064        False              False           False        False
3065        False              False           False        False
3066        False              False           False        False
3067        False              False           False        False
3068        False              False           False        False

      Building_Painted  Building_Fenced  Garden  Settlement  \
0                False            False   False       False
1                False            False   False       False
2                False            False   False       False
3                False            False   False       False
4                False            False   False       False
5                False            False   False       False
6                False            False   False       False
7                False            False   False       False
8                False            False   False       False
9                False            False   False       False
10               False            False   False       False
11               False            False   False       False
12               False            False   False       False
13               False            False   False       False
14               False            False   False       False
15               False            False   False       False
16               False            False   False       False
17               False            False   False       False
18               False            False   False       False
19               False            False   False       False
20               False            False   False       False
21               False            False   False       False
22               False            False   False       False
23               False            False   False       False
24               False            False   False       False
25               False            False   False       False
26               False            False   False       False
27               False            False   False       False
28               False            False   False       False
29               False            False   False       False
...                ...              ...     ...         ...
3039             False            False   False       False
3040             False            False   False       False
3041             False            False   False       False
3042             False            False   False       False
3043             False            False   False       False
3044             False            False   False       False
3045             False            False   False       False
3046             False            False   False       False
3047             False            False   False       False
3048             False            False   False       False
3049             False            False   False       False
3050             False            False   False       False
3051             False            False   False       False
3052             False            False   False       False
3053             False            False   False       False
3054             False            False   False       False
3055             False            False   False       False
3056             False            False   False       False
3057             False            False   False       False
3058             False            False   False       False
3059             False            False   False       False
3060             False            False   False       False
3061             False            False   False       False
3062             False            False   False       False
3063             False            False   False       False
3064             False            False   False       False
3065             False            False   False       False
3066             False            False   False       False
3067             False            False   False       False
3068             False            False   False       False

      Building Dimension  Building_Type  Date_of_Occupancy  NumberOfWindows  \
0                  False          False              False            False
1                  False          False              False            False
2                  False          False              False            False
3                  False          False              False            False
4                  False          False              False            False
5                  False          False              False            False
6                  False          False               True            False
7                  False          False              False            False
8                  False          False               True            False
9                  False          False               True            False
10                 False          False              False            False
11                 False          False              False            False
12                 False          False              False            False
13                 False          False              False            False
14                 False          False              False            False
15                 False          False              False            False
16                 False          False              False            False
17                 False          False              False            False
18                 False          False              False            False
19                 False          False              False            False
20                 False          False              False            False
21                 False          False               True            False
22                 False          False              False            False
23                 False          False              False            False
24                 False          False              False            False
25                 False          False              False            False
26                 False          False               True            False
27                 False          False               True            False
28                 False          False              False            False
29                 False          False              False            False
...                  ...            ...                ...              ...
3039               False          False               True            False
3040               False          False               True            False
3041               False          False              False            False
3042               False          False               True            False
3043               False          False               True            False
3044               False          False               True            False
3045               False          False               True            False
3046               False          False               True            False
3047               False          False               True            False
3048               False          False               True            False
3049               False          False              False            False
3050               False          False               True            False
3051               False          False               True            False
3052               False          False              False            False
3053               False          False               True            False
3054               False          False               True            False
3055               False          False               True            False
3056                True          False              False            False
3057                True          False              False            False
3058                True          False              False            False
3059                True          False              False            False
3060                True          False              False            False
3061                True          False              False            False
3062                True          False              False            False
3063                True          False              False            False
3064                True          False              False            False
3065                True          False              False            False
3066                True          False              False            False
3067                True          False              False            False
3068                True          False              False            False

      Geo_Code
0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
...        ...
3039     False
3040     False
3041     False
3042     False
3043     False
3044     False
3045     False
3046     False
3047     False
3048     False
3049     False
3050     False
3051     False
3052     False
3053     False
3054     False
3055     False
3056      True
3057      True
3058      True
3059      True
3060      True
3061      True
3062      True
3063      True
3064      True
3065      True
3066      True
3067      True
3068      True

[3069 rows x 13 columns]>

In [15]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 14 columns):
Customer Id           7160 non-null object
YearOfObservation     7160 non-null int64
Insured_Period        7160 non-null float64
Residential           7160 non-null int64
Building_Painted      7160 non-null object
Building_Fenced       7160 non-null object
Garden                7153 non-null object
Settlement            7160 non-null object
Building Dimension    7054 non-null float64
Building_Type         7160 non-null int64
Date_of_Occupancy     6652 non-null float64
NumberOfWindows       7160 non-null object
Geo_Code              7058 non-null object
Claim                 7160 non-null int64
dtypes: float64(3), int64(4), object(7)
memory usage: 783.2+ KB

In [16]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 13 columns):
Customer Id           3069 non-null object
YearOfObservation     3069 non-null int64
Insured_Period        3069 non-null float64
Residential           3069 non-null int64
Building_Painted      3069 non-null object
Building_Fenced       3069 non-null object
Garden                3065 non-null object
Settlement            3069 non-null object
Building Dimension    3056 non-null float64
Building_Type         3069 non-null int64
Date_of_Occupancy     2341 non-null float64
NumberOfWindows       3069 non-null object
Geo_Code              3056 non-null object
dtypes: float64(3), int64(3), object(7)
memory usage: 311.8+ KB

In [17]:
train.describe()

,YearOfObservation,Insured_Period,Residential,Building Dimension,Building_Type,Date_of_Occupancy,Claim
count,7160.000000,7160.000000,7160.000000,7054.000000,7160.000000,6652.000000,7160.000000
mean,2013.669553,0.909758,0.305447,1883.727530,2.186034,1964.456404,0.228212
std,1.383769,0.239756,0.460629,2278.157745,0.940632,36.002014,0.419709
min,2012.000000,0.000000,0.000000,1.000000,1.000000,1545.000000,0.000000
25%,2012.000000,0.997268,0.000000,528.000000,2.000000,1960.000000,0.000000
50%,2013.000000,1.000000,0.000000,1083.000000,2.000000,1970.000000,0.000000
75%,2015.000000,1.000000,1.000000,2289.750000,3.000000,1980.000000,0.000000
max,2016.000000,1.000000,1.000000,20940.000000,4.000000,2016.000000,1.000000

In [18]:
test.describe()

,YearOfObservation,Insured_Period,Residential,Building Dimension,Building_Type,Date_of_Occupancy
count,3069.000000,3069.000000,3069.000000,3056.000000,3069.000000,2341.000000
mean,2013.593679,0.922806,0.224177,1666.790576,2.359400,1966.781717
std,1.372138,0.219066,0.417107,2251.180599,0.998464,25.238702
min,2012.000000,0.000000,0.000000,1.000000,1.000000,1750.000000
25%,2012.000000,1.000000,0.000000,470.000000,2.000000,1960.000000
50%,2013.000000,1.000000,0.000000,900.000000,2.000000,1968.000000
75%,2015.000000,1.000000,0.000000,1957.000000,3.000000,1980.000000
max,2016.000000,1.000000,1.000000,30745.000000,4.000000,2012.000000

In [19]:
train=train.fillna(-999)

In [20]:
test=test.fillna(-999)

In [21]:
train.isnull().sum()

Customer Id           0
YearOfObservation     0
Insured_Period        0
Residential           0
Building_Painted      0
Building_Fenced       0
Garden                0
Settlement            0
Building Dimension    0
Building_Type         0
Date_of_Occupancy     0
NumberOfWindows       0
Geo_Code              0
Claim                 0
dtype: int64

In [22]:
test.isnull().sum()

Customer Id           0
YearOfObservation     0
Insured_Period        0
Residential           0
Building_Painted      0
Building_Fenced       0
Garden                0
Settlement            0
Building Dimension    0
Building_Type         0
Date_of_Occupancy     0
NumberOfWindows       0
Geo_Code              0
dtype: int64

In [23]:
train.duplicated()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
7130    False
7131    False
7132    False
7133    False
7134    False
7135    False
7136    False
7137    False
7138    False
7139    False
7140    False
7141    False
7142    False
7143    False
7144    False
7145    False
7146    False
7147    False
7148    False
7149    False
7150    False
7151    False
7152    False
7153    False
7154    False
7155    False
7156    False
7157    False
7158    False
7159    False
Length: 7160, dtype: bool

In [24]:
test.duplicated()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
3039    False
3040    False
3041    False
3042    False
3043    False
3044    False
3045    False
3046    False
3047    False
3048    False
3049    False
3050    False
3051    False
3052    False
3053    False
3054    False
3055    False
3056    False
3057    False
3058    False
3059    False
3060    False
3061    False
3062    False
3063    False
3064    False
3065    False
3066    False
3067    False
3068    False
Length: 3069, dtype: bool

In [26]:
train = train.drop('Customer Id',axis=1)

In [27]:
train.head()

,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,2013,1.0,0,N,V,V,U,290.0,1,1960.0,.,1053,0
1,2015,1.0,0,V,N,O,R,490.0,1,1850.0,4,1053,0
2,2014,1.0,0,N,V,V,U,595.0,1,1960.0,.,1053,0
3,2013,1.0,0,V,V,V,U,2840.0,1,1960.0,.,1053,0
4,2014,1.0,0,V,N,O,R,680.0,1,1800.0,3,1053,0

In [28]:
test = test.drop('Customer Id',axis=1)

In [29]:
test.head()

,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code
0,2013,1.000000,0,V,N,O,R,300.0,1,1960.0,3,3310
1,2016,0.997268,0,V,N,O,R,300.0,1,1960.0,3,3310
2,2013,0.369863,0,V,V,V,U,790.0,1,1960.0,.,3310
3,2014,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321
4,2016,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321

In [31]:
train['Claim'] = train['Claim'].replace('no',0)
train['Claim'] = train['Claim'].replace('yes', 1)

In [32]:
X=train.drop('Claim',axis=1)
y=train['Claim']

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=7,shuffle=True,stratify=y)

C:\Users\user\Anaconda3\Desktop\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [44]:
cat_feat_ind = np.where(X.dtypes==np.object)[0]

In [45]:
cat_feat_ind

array([ 3,  4,  5,  6, 10, 11], dtype=int64)

In [46]:
import catboost

In [47]:
from sklearn.metrics import*

In [ ]:
from catboost import CatBoostClassifier
cat = CatBoostClassifier(cat_features=cat_feat_ind,learning_rate = 0.1,iterations = 500,max_depth=10,eval_metric ='AUC',random_seed=8679)
eval_set = [(X_test,y_test)]
cat.fit(X_train,y_train,early_stopping_rounds=300,eval_set=eval_set)
y_cat=cat.predict_proba(X_test)[:,1]
print(roc_auc_score(y_test,y_cat))

0:	test: 0.6874936	best: 0.6874936 (0)	total: 340ms	remaining: 2m 49s
1:	test: 0.6811989	best: 0.6874936 (0)	total: 439ms	remaining: 1m 49s
2:	test: 0.6852879	best: 0.6874936 (0)	total: 654ms	remaining: 1m 48s
3:	test: 0.6948773	best: 0.6948773 (3)	total: 829ms	remaining: 1m 42s
4:	test: 0.6968215	best: 0.6968215 (4)	total: 954ms	remaining: 1m 34s
5:	test: 0.7018169	best: 0.7018169 (5)	total: 2.36s	remaining: 3m 14s
6:	test: 0.7020922	best: 0.7020922 (6)	total: 2.45s	remaining: 2m 52s
7:	test: 0.7024991	best: 0.7024991 (7)	total: 2.57s	remaining: 2m 38s
8:	test: 0.7024991	best: 0.7024991 (7)	total: 2.62s	remaining: 2m 22s
9:	test: 0.6993994	best: 0.7024991 (7)	total: 2.83s	remaining: 2m 18s
10:	test: 0.6979659	best: 0.7024991 (7)	total: 3.01s	remaining: 2m 13s
11:	test: 0.7014529	best: 0.7024991 (7)	total: 3.3s	remaining: 2m 14s
12:	test: 0.7019746	best: 0.7024991 (7)	total: 3.38s	remaining: 2m 6s
13:	test: 0.7019207	best: 0.7024991 (7)	total: 3.58s	remaining: 2m 4s
14:	test: 0.7022251	best: 0.7024991 (7)	total: 3.99s	remaining: 2m 8s
15:	test: 0.7024506	best: 0.7024991 (7)	total: 4.16s	remaining: 2m 5s
16:	test: 0.7034649	best: 0.7034649 (16)	total: 4.37s	remaining: 2m 4s
17:	test: 0.7034649	best: 0.7034649 (16)	total: 4.45s	remaining: 1m 59s
18:	test: 0.7038662	best: 0.7038662 (18)	total: 4.64s	remaining: 1m 57s
19:	test: 0.7049137	best: 0.7049137 (19)	total: 5.26s	remaining: 2m 6s
20:	test: 0.7045401	best: 0.7049137 (19)	total: 5.38s	remaining: 2m 2s
21:	test: 0.7049677	best: 0.7049677 (21)	total: 6.02s	remaining: 2m 10s
22:	test: 0.7049857	best: 0.7049857 (22)	total: 6.12s	remaining: 2m 6s
23:	test: 0.7053012	best: 0.7053012 (23)	total: 6.47s	remaining: 2m 8s
24:	test: 0.7058768	best: 0.7058768 (24)	total: 7.09s	remaining: 2m 14s
25:	test: 0.7063943	best: 0.7063943 (25)	total: 7.24s	remaining: 2m 11s
26:	test: 0.7075567	best: 0.7075567 (26)	total: 8.91s	remaining: 2m 36s
27:	test: 0.7073906	best: 0.7075567 (26)	total: 9.04s	remaining: 2m 32s
28:	test: 0.7076037	best: 0.7076037 (28)	total: 9.21s	remaining: 2m 29s
29:	test: 0.7079013	best: 0.7079013 (29)	total: 9.6s	remaining: 2m 30s
30:	test: 0.7079262	best: 0.7079262 (30)	total: 9.77s	remaining: 2m 27s
31:	test: 0.7077809	best: 0.7079262 (30)	total: 9.87s	remaining: 2m 24s
32:	test: 0.7078390	best: 0.7079262 (30)	total: 9.96s	remaining: 2m 20s
33:	test: 0.7080590	best: 0.7080590 (33)	total: 10.4s	remaining: 2m 21s
34:	test: 0.7084354	best: 0.7084354 (34)	total: 10.5s	remaining: 2m 20s
35:	test: 0.7084409	best: 0.7084409 (35)	total: 10.6s	remaining: 2m 17s
36:	test: 0.7080286	best: 0.7084409 (35)	total: 10.8s	remaining: 2m 15s
37:	test: 0.7083828	best: 0.7084409 (35)	total: 11.4s	remaining: 2m 18s
38:	test: 0.7082832	best: 0.7084409 (35)	total: 11.7s	remaining: 2m 17s
39:	test: 0.7082832	best: 0.7084409 (35)	total: 11.8s	remaining: 2m 15s
40:	test: 0.7082832	best: 0.7084409 (35)	total: 11.9s	remaining: 2m 13s
41:	test: 0.7087606	best: 0.7087606 (41)	total: 12.3s	remaining: 2m 13s
42:	test: 0.7086443	best: 0.7087606 (41)	total: 12.4s	remaining: 2m 11s
43:	test: 0.7080120	best: 0.7087606 (41)	total: 12.6s	remaining: 2m 10s
44:	test: 0.7081171	best: 0.7087606 (41)	total: 13s	remaining: 2m 11s
45:	test: 0.7080839	best: 0.7087606 (41)	total: 13.1s	remaining: 2m 9s
46:	test: 0.7080645	best: 0.7087606 (41)	total: 13.2s	remaining: 2m 7s
47:	test: 0.7081144	best: 0.7087606 (41)	total: 13.4s	remaining: 2m 6s
48:	test: 0.7083939	best: 0.7087606 (41)	total: 13.5s	remaining: 2m 4s
49:	test: 0.7079857	best: 0.7087606 (41)	total: 13.7s	remaining: 2m 3s
50:	test: 0.7079718	best: 0.7087606 (41)	total: 13.9s	remaining: 2m 2s
51:	test: 0.7087896	best: 0.7087896 (51)	total: 14.2s	remaining: 2m 2s
52:	test: 0.7091217	best: 0.7091217 (52)	total: 14.5s	remaining: 2m 2s
53:	test: 0.7092186	best: 0.7092186 (53)	total: 14.6s	remaining: 2m
54:	test: 0.7091688	best: 0.7092186 (53)	total: 14.7s	remaining: 1m 59s
55:	test: 0.7093653	best: 0.7093653 (55)	total: 14.9s	remaining: 1m 58s
56:	test: 0.7096863	best: 0.7096863 (56)	total: 15.2s	remaining: 1m 57s
57:	test: 0.7101402	best: 0.7101402 (57)	total: 15.5s	remaining: 1m 58s
58:	test: 0.7104280	best: 0.7104280 (58)	total: 15.8s	remaining: 1m 57s
59:	test: 0.7105539	best: 0.7105539 (59)	total: 16s	remaining: 1m 57s
60:	test: 0.7101139	best: 0.7105539 (59)	total: 16.3s	remaining: 1m 57s
61:	test: 0.7107988	best: 0.7107988 (61)	total: 18.1s	remaining: 2m 8s
62:	test: 0.7107214	best: 0.7107988 (61)	total: 18.2s	remaining: 2m 6s
63:	test: 0.7109843	best: 0.7109843 (63)	total: 18.4s	remaining: 2m 5s
64:	test: 0.7112652	best: 0.7112652 (64)	total: 18.7s	remaining: 2m 4s
65:	test: 0.7112652	best: 0.7112652 (64)	total: 18.8s	remaining: 2m 3s
66:	test: 0.7112679	best: 0.7112679 (66)	total: 19s	remaining: 2m 2s
67:	test: 0.7109428	best: 0.7112679 (66)	total: 21.1s	remaining: 2m 14s
68:	test: 0.7109345	best: 0.7112679 (66)	total: 21.2s	remaining: 2m 12s
69:	test: 0.7109483	best: 0.7112679 (66)	total: 21.4s	remaining: 2m 11s
70:	test: 0.7110396	best: 0.7112679 (66)	total: 21.7s	remaining: 2m 11s
71:	test: 0.7111379	best: 0.7112679 (66)	total: 21.9s	remaining: 2m 9s
72:	test: 0.7103989	best: 0.7112679 (66)	total: 23.5s	remaining: 2m 17s
73:	test: 0.7103989	best: 0.7112679 (66)	total: 23.6s	remaining: 2m 15s
74:	test: 0.7102467	best: 0.7112679 (66)	total: 23.8s	remaining: 2m 14s
75:	test: 0.7102523	best: 0.7112679 (66)	total: 24s	remaining: 2m 13s
76:	test: 0.7102564	best: 0.7112679 (66)	total: 24.1s	remaining: 2m 12s
77:	test: 0.7102869	best: 0.7112679 (66)	total: 24.3s	remaining: 2m 11s
78:	test: 0.7105110	best: 0.7112679 (66)	total: 24.7s	remaining: 2m 11s
79:	test: 0.7105304	best: 0.7112679 (66)	total: 24.8s	remaining: 2m 10s
80:	test: 0.7106466	best: 0.7112679 (66)	total: 24.9s	remaining: 2m 9s
81:	test: 0.7105940	best: 0.7112679 (66)	total: 25.1s	remaining: 2m 8s
82:	test: 0.7105996	best: 0.7112679 (66)	total: 25.2s	remaining: 2m 6s
83:	test: 0.7106660	best: 0.7112679 (66)	total: 26.2s	remaining: 2m 9s
84:	test: 0.7107850	best: 0.7112679 (66)	total: 26.8s	remaining: 2m 10s
85:	test: 0.7107822	best: 0.7112679 (66)	total: 26.9s	remaining: 2m 9s
86:	test: 0.7109594	best: 0.7112679 (66)	total: 27s	remaining: 2m 8s
87:	test: 0.7109732	best: 0.7112679 (66)	total: 27.2s	remaining: 2m 7s
88:	test: 0.7109621	best: 0.7112679 (66)	total: 27.4s	remaining: 2m 6s
89:	test: 0.7109455	best: 0.7112679 (66)	total: 27.6s	remaining: 2m 5s
90:	test: 0.7107878	best: 0.7112679 (66)	total: 27.7s	remaining: 2m 4s
91:	test: 0.7108653	best: 0.7112679 (66)	total: 27.9s	remaining: 2m 3s
92:	test: 0.7109801	best: 0.7112679 (66)	total: 28.3s	remaining: 2m 3s
93:	test: 0.7109248	best: 0.7112679 (66)	total: 28.6s	remaining: 2m 3s
94:	test: 0.7113399	best: 0.7113399 (94)	total: 29s	remaining: 2m 3s
95:	test: 0.7111738	best: 0.7113399 (94)	total: 29.4s	remaining: 2m 3s
96:	test: 0.7113731	best: 0.7113731 (96)	total: 30.6s	remaining: 2m 7s
97:	test: 0.7113427	best: 0.7113731 (96)	total: 30.9s	remaining: 2m 6s
98:	test: 0.7114271	best: 0.7114271 (98)	total: 31.2s	remaining: 2m 6s
99:	test: 0.7114852	best: 0.7114852 (99)	total: 31.4s	remaining: 2m 5s
100:	test: 0.7115654	best: 0.7115654 (100)	total: 31.6s	remaining: 2m 4s
101:	test: 0.7115654	best: 0.7115654 (100)	total: 31.7s	remaining: 2m 3s
102:	test: 0.7115876	best: 0.7115876 (102)	total: 31.9s	remaining: 2m 3s
103:	test: 0.7117841	best: 0.7117841 (103)	total: 33.5s	remaining: 2m 7s
104:	test: 0.7119252	best: 0.7119252 (104)	total: 35.6s	remaining: 2m 13s
105:	test: 0.7120027	best: 0.7120027 (105)	total: 36.1s	remaining: 2m 14s
106:	test: 0.7119252	best: 0.7120027 (105)	total: 38.3s	remaining: 2m 20s
107:	test: 0.7121826	best: 0.7121826 (107)	total: 40.5s	remaining: 2m 26s
108:	test: 0.7119723	best: 0.7121826 (107)	total: 42.5s	remaining: 2m 32s
109:	test: 0.7120664	best: 0.7121826 (107)	total: 43s	remaining: 2m 32s
110:	test: 0.7120304	best: 0.7121826 (107)	total: 45.1s	remaining: 2m 37s
111:	test: 0.7111780	best: 0.7121826 (107)	total: 47s	remaining: 2m 42s
112:	test: 0.7111503	best: 0.7121826 (107)	total: 47.2s	remaining: 2m 41s
113:	test: 0.7113385	best: 0.7121826 (107)	total: 48.9s	remaining: 2m 45s
114:	test: 0.7114852	best: 0.7121826 (107)	total: 50.7s	remaining: 2m 49s

115:	test: 0.7119280	best: 0.7121826 (107)	total: 52.4s	remaining: 2m 53s
116:	test: 0.7123154	best: 0.7123154 (116)	total: 54.2s	remaining: 2m 57s
117:	test: 0.7125175	best: 0.7125175 (117)	total: 55.9s	remaining: 3m
118:	test: 0.7124732	best: 0.7125175 (117)	total: 57.4s	remaining: 3m 3s
119:	test: 0.7128496	best: 0.7128496 (119)	total: 59s	remaining: 3m 6s
120:	test: 0.7128523	best: 0.7128523 (120)	total: 1m	remaining: 3m 10s
121:	test: 0.7126448	best: 0.7128523 (120)	total: 1m 2s	remaining: 3m 13s
122:	test: 0.7126780	best: 0.7128523 (120)	total: 1m 3s	remaining: 3m 15s
123:	test: 0.7126558	best: 0.7128523 (120)	total: 1m 4s	remaining: 3m 14s
124:	test: 0.7123265	best: 0.7128523 (120)	total: 1m 5s	remaining: 3m 17s
125:	test: 0.7122795	best: 0.7128523 (120)	total: 1m 7s	remaining: 3m 20s
126:	test: 0.7122712	best: 0.7128523 (120)	total: 1m 9s	remaining: 3m 22s
127:	test: 0.7136937	best: 0.7136937 (127)	total: 1m 10s	remaining: 3m 25s
128:	test: 0.7132536	best: 0.7136937 (127)	total: 1m 12s	remaining: 3m 28s
129:	test: 0.7132536	best: 0.7136937 (127)	total: 1m 12s	remaining: 3m 26s
130:	test: 0.7132426	best: 0.7136937 (127)	total: 1m 13s	remaining: 3m 27s
131:	test: 0.7132924	best: 0.7136937 (127)	total: 1m 15s	remaining: 3m 29s
132:	test: 0.7133228	best: 0.7136937 (127)	total: 1m 16s	remaining: 3m 32s
133:	test: 0.7133560	best: 0.7136937 (127)	total: 1m 18s	remaining: 3m 33s
134:	test: 0.7132813	best: 0.7136937 (127)	total: 1m 19s	remaining: 3m 35s
135:	test: 0.7128662	best: 0.7136937 (127)	total: 1m 21s	remaining: 3m 38s
136:	test: 0.7128855	best: 0.7136937 (127)	total: 1m 23s	remaining: 3m 40s
137:	test: 0.7128413	best: 0.7136937 (127)	total: 1m 24s	remaining: 3m 41s
138:	test: 0.7128330	best: 0.7136937 (127)	total: 1m 24s	remaining: 3m 40s
139:	test: 0.7126558	best: 0.7136937 (127)	total: 1m 26s	remaining: 3m 41s
140:	test: 0.7126586	best: 0.7136937 (127)	total: 1m 26s	remaining: 3m 40s
141:	test: 0.7126697	best: 0.7136937 (127)	total: 1m 26s	remaining: 3m 38s
142:	test: 0.7131180	best: 0.7136937 (127)	total: 1m 27s	remaining: 3m 39s
143:	test: 0.7129409	best: 0.7136937 (127)	total: 1m 29s	remaining: 3m 41s
144:	test: 0.7134058	best: 0.7136937 (127)	total: 1m 31s	remaining: 3m 44s
145:	test: 0.7134861	best: 0.7136937 (127)	total: 1m 33s	remaining: 3m 46s
146:	test: 0.7135138	best: 0.7136937 (127)	total: 1m 35s	remaining: 3m 48s
147:	test: 0.7135138	best: 0.7136937 (127)	total: 1m 36s	remaining: 3m 50s
148:	test: 0.7135636	best: 0.7136937 (127)	total: 1m 38s	remaining: 3m 51s
149:	test: 0.7134889	best: 0.7136937 (127)	total: 1m 40s	remaining: 3m 53s
150:	test: 0.7134058	best: 0.7136937 (127)	total: 1m 40s	remaining: 3m 51s
151:	test: 0.7126074	best: 0.7136937 (127)	total: 1m 42s	remaining: 3m 53s
152:	test: 0.7126019	best: 0.7136937 (127)	total: 1m 43s	remaining: 3m 55s
153:	test: 0.7126351	best: 0.7136937 (127)	total: 1m 45s	remaining: 3m 56s
154:	test: 0.7126628	best: 0.7136937 (127)	total: 1m 46s	remaining: 3m 58s
155:	test: 0.7127209	best: 0.7136937 (127)	total: 1m 48s	remaining: 3m 59s
156:	test: 0.7127070	best: 0.7136937 (127)	total: 1m 50s	remaining: 4m
157:	test: 0.7124386	best: 0.7136937 (127)	total: 1m 51s	remaining: 4m 1s
158:	test: 0.7122587	best: 0.7136937 (127)	total: 1m 53s	remaining: 4m 2s
159:	test: 0.7122172	best: 0.7136937 (127)	total: 1m 54s	remaining: 4m 3s
160:	test: 0.7123445	best: 0.7136937 (127)	total: 1m 56s	remaining: 4m 5s
161:	test: 0.7124109	best: 0.7136937 (127)	total: 1m 58s	remaining: 4m 6s
162:	test: 0.7127070	best: 0.7136937 (127)	total: 1m 59s	remaining: 4m 6s
163:	test: 0.7123279	best: 0.7136937 (127)	total: 2m	remaining: 4m 7s
164:	test: 0.7121923	best: 0.7136937 (127)	total: 2m 2s	remaining: 4m 8s
165:	test: 0.7122172	best: 0.7136937 (127)	total: 2m 2s	remaining: 4m 6s
166:	test: 0.7122144	best: 0.7136937 (127)	total: 2m 3s	remaining: 4m 5s
167:	test: 0.7122144	best: 0.7136937 (127)	total: 2m 3s	remaining: 4m 4s
168:	test: 0.7121618	best: 0.7136937 (127)	total: 2m 5s	remaining: 4m 4s
169:	test: 0.7120927	best: 0.7136937 (127)	total: 2m 5s	remaining: 4m 3s
170:	test: 0.7122504	best: 0.7136937 (127)	total: 2m 6s	remaining: 4m 4s
171:	test: 0.7123390	best: 0.7136937 (127)	total: 2m 8s	remaining: 4m 4s
172:	test: 0.7120567	best: 0.7136937 (127)	total: 2m 9s	remaining: 4m 5s
173:	test: 0.7122366	best: 0.7136937 (127)	total: 2m 11s	remaining: 4m 5s
174:	test: 0.7130779	best: 0.7136937 (127)	total: 2m 12s	remaining: 4m 6s
175:	test: 0.7137421	best: 0.7137421 (175)	total: 2m 13s	remaining: 4m 6s
176:	test: 0.7137947	best: 0.7137947 (176)	total: 2m 15s	remaining: 4m 6s
177:	test: 0.7138196	best: 0.7138196 (177)	total: 2m 16s	remaining: 4m 6s
178:	test: 0.7136286	best: 0.7138196 (177)	total: 2m 17s	remaining: 4m 7s
179:	test: 0.7136203	best: 0.7138196 (177)	total: 2m 18s	remaining: 4m 6s
180:	test: 0.7133851	best: 0.7138196 (177)	total: 2m 19s	remaining: 4m 6s
181:	test: 0.7133851	best: 0.7138196 (177)	total: 2m 20s	remaining: 4m 4s
182:	test: 0.7137034	best: 0.7138196 (177)	total: 2m 20s	remaining: 4m 4s
183:	test: 0.7136618	best: 0.7138196 (177)	total: 2m 22s	remaining: 4m 4s
184:	test: 0.7136701	best: 0.7138196 (177)	total: 2m 24s	remaining: 4m 5s
185:	test: 0.7136950	best: 0.7138196 (177)	total: 2m 26s	remaining: 4m 7s
186:	test: 0.7136535	best: 0.7138196 (177)	total: 2m 28s	remaining: 4m 8s
187:	test: 0.7136674	best: 0.7138196 (177)	total: 2m 30s	remaining: 4m 9s
188:	test: 0.7136646	best: 0.7138196 (177)	total: 2m 31s	remaining: 4m 9s
189:	test: 0.7136591	best: 0.7138196 (177)	total: 2m 33s	remaining: 4m 10s
190:	test: 0.7136923	best: 0.7138196 (177)	total: 2m 34s	remaining: 4m 10s
191:	test: 0.7136535	best: 0.7138196 (177)	total: 2m 36s	remaining: 4m 10s
192:	test: 0.7136369	best: 0.7138196 (177)	total: 2m 38s	remaining: 4m 11s
193:	test: 0.7136895	best: 0.7138196 (177)	total: 2m 39s	remaining: 4m 11s
194:	test: 0.7140050	best: 0.7140050 (194)	total: 2m 41s	remaining: 4m 12s
195:	test: 0.7145585	best: 0.7145585 (195)	total: 2m 42s	remaining: 4m 12s
196:	test: 0.7145391	best: 0.7145585 (195)	total: 2m 44s	remaining: 4m 13s
197:	test: 0.7143620	best: 0.7145585 (195)	total: 2m 46s	remaining: 4m 13s
198:	test: 0.7142347	best: 0.7145585 (195)	total: 2m 47s	remaining: 4m 13s
199:	test: 0.7141987	best: 0.7145585 (195)	total: 2m 48s	remaining: 4m 12s
200:	test: 0.7141517	best: 0.7145585 (195)	total: 2m 49s	remaining: 4m 12s
201:	test: 0.7142901	best: 0.7145585 (195)	total: 2m 51s	remaining: 4m 12s
202:	test: 0.7141323	best: 0.7145585 (195)	total: 2m 53s	remaining: 4m 13s
203:	test: 0.7143371	best: 0.7145585 (195)	total: 2m 55s	remaining: 4m 14s
204:	test: 0.7144395	best: 0.7145585 (195)	total: 2m 57s	remaining: 4m 15s
205:	test: 0.7144340	best: 0.7145585 (195)	total: 2m 57s	remaining: 4m 13s
206:	test: 0.7143897	best: 0.7145585 (195)	total: 2m 59s	remaining: 4m 14s
207:	test: 0.7144063	best: 0.7145585 (195)	total: 3m 1s	remaining: 4m 14s
208:	test: 0.7143980	best: 0.7145585 (195)	total: 3m 2s	remaining: 4m 14s
209:	test: 0.7141212	best: 0.7145585 (195)	total: 3m 4s	remaining: 4m 14s
210:	test: 0.7140853	best: 0.7145585 (195)	total: 3m 5s	remaining: 4m 14s
211:	test: 0.7139026	best: 0.7145585 (195)	total: 3m 7s	remaining: 4m 14s
212:	test: 0.7137504	best: 0.7145585 (195)	total: 3m 8s	remaining: 4m 14s
213:	test: 0.7137698	best: 0.7145585 (195)	total: 3m 9s	remaining: 4m 12s
214:	test: 0.7138694	best: 0.7145585 (195)	total: 3m 10s	remaining: 4m 12s
215:	test: 0.7140355	best: 0.7145585 (195)	total: 3m 12s	remaining: 4m 12s
216:	test: 0.7140825	best: 0.7145585 (195)	total: 3m 13s	remaining: 4m 12s
217:	test: 0.7141351	best: 0.7145585 (195)	total: 3m 15s	remaining: 4m 12s
218:	test: 0.7130641	best: 0.7145585 (195)	total: 3m 16s	remaining: 4m 12s
219:	test: 0.7130419	best: 0.7145585 (195)	total: 3m 18s	remaining: 4m 12s
220:	test: 0.7129893	best: 0.7145585 (195)	total: 3m 19s	remaining: 4m 11s